<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MiaoXinxin</AssemblyName>
    <Version>0.8.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>MiaoXinxin.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\DockCatApp\DockCat\Resources\DefaultCat\**\*">
      <Link>Resources\DefaultPet\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
